// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/api.tsx";
import * as $3 from "./routes/index.tsx";
import * as $4 from "./routes/sign-in/index.tsx";
import * as $$0 from "./islands/GoogleSignIn.tsx";
import * as $$1 from "./islands/GoogleSignIn/handle-credential-response.fn.ts";
import * as $$2 from "./islands/GoogleSignIn/load-google-signin.fn.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/api.tsx": $2,
    "./routes/index.tsx": $3,
    "./routes/sign-in/index.tsx": $4,
  },
  islands: {
    "./islands/GoogleSignIn.tsx": $$0,
    "./islands/GoogleSignIn/handle-credential-response.fn.ts": $$1,
    "./islands/GoogleSignIn/load-google-signin.fn.ts": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
